# -*- coding: utf-8 -*-
"""relu_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P3bPj7m_dp3BTkBmf-TtVJ3m2ylyJzXH
"""

import numpy as np
import matplotlib.pyplot as plt

# ReLU
def relu(x):
    return np.maximum(0, x)

# Improvements
def leaky_relu(x, alpha=0.01):
    return np.where(x > 0, x, alpha * x)

def prelu(x, alpha=0.1):
    return np.where(x > 0, x, alpha * x)

def elu(x, alpha=1.0):
    return np.where(x > 0, x, alpha * (np.exp(x) - 1))

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def swish(x):
    return x * sigmoid(x)


# 1. Positive Region (Advantage)
x_pos = np.linspace(0, 10, 200)

plt.figure(figsize=(8,5))
plt.plot(x_pos, relu(x_pos), label="ReLU")
plt.title("ReLU (Positive Region - Advantage)")
plt.xlabel("Input")
plt.ylabel("Output")
plt.legend()
plt.grid()
plt.show()

# 2. Negative Region (Flaw)
x_neg = np.linspace(-10, 0, 200)

plt.figure(figsize=(8,5))
plt.plot(x_neg, relu(x_neg), label="ReLU")
plt.title("ReLU (Negative Region - Dying ReLU Problem)")
plt.xlabel("Input")
plt.ylabel("Output")
plt.legend()
plt.grid()
plt.show()

# 3. Improvements (Solution)
x = np.linspace(-10, 10, 400)

plt.figure(figsize=(10,6))
plt.plot(x, relu(x), linewidth=3, linestyle='--', label="ReLU")
plt.plot(x, leaky_relu(x), label="Leaky ReLU")
plt.plot(x, prelu(x), label="PReLU")
plt.plot(x, elu(x), label="ELU")
plt.plot(x, swish(x), label="Swish")

plt.title("Improved Activation Functions vs ReLU")
plt.xlabel("Input")
plt.ylabel("Output")
plt.legend()
plt.grid()
plt.show()